spring:
#  redis:
#    host: localhost
#    port: 6379
  redis:
    host: redis-15218.c305.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 15218
    password: TOqtq3wNzOzfyB1s5flx9v3DleY3a0sr
  data:
    mongodb:
      uri: mongodb+srv://anikpal_:mongo2020@cluster0.ppfaw.mongodb.net/dinchariyadb?retryWrites=true&w=majority&appName=Cluster0
      database: dinchariyadb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: code.space.ap@gmail.com
    password: jwvfimfwjkkoupxo   # <-- This should be an App Password, not normal Gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true   # <--- important to avoid 530 error

server:
  port: 8080

logging:
  level:
    #    root: ERROR
    root: INFO